services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      MEMORY: 26G
      TYPE: PAPER
      PAPER_CHANNEL: EXPERIMENTAL
      ENABLE_WHITELIST: true
      WHITELIST: '${WHITELIST}'
      RCON_PASSWORD: '${RCON_PWD}'
    ports:
      - "25565:25565"
      - "24454:24454/udp"
    volumes:
      - /home/MinecraftServer:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}
