services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      MEMORY: 26G
      TYPE: SPIGOT
      ENABLE_WHITELIST: true
      WHITELIST: '${WHITELIST}'
      RCON_PASSWORD: '${RCON_PWD}'
    ports:
      - "25565:25565"
    volumes:
      - data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}
